source "https://rubygems.org"

gem "attr_extras"
gem "dead_end"
gem "minitest", "~> 5.0"
gem "minitest-reporters"
gem "pastel"
gem "pry"
gem "pry-byebug"
gem "rake"
gem "rubocop"
gem "rubycritic"
gem "tabulo"
gem "tty-pie"
gem "unicode_plot"
